site_name: 'グラッチェコイン オンラインマニュアル'
theme:
  name: 'material'
  lacale: ja
  language: ja
  favicon: images/GrazieCoin_p.png
  logo: images/GrazieCoin_p.png
  palette:
    primary:  blue
  features:
    # 左メニューにTOC(目次)を含める
    # 指定しないと、右側に目次が出る
    # - toc.integrate
    - navigation.instant
    - navigation.top
    - navigation.tabs
markdown_extensions:
  # アイコン・絵文字の設定
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # アラート修飾の設定
  - admonition
  # コンテンツ折りたたみ設定
  - pymdownx.details
  - toc:
      toc_depth: 3
extra:
  search:
    language: jp

extra_javascript:
    - 'libs/lightbox-plus-jquery.min.js'
extra_css:
    - 'libs/lightbox.min.css'
nav:
  - 'もくじ': 'index.md'
  - 'クイックスタート':
    - 'グラッチェする！': 'howto/howto01.md'
    - 'コインを商品と交換する！': 'howto/howto02.md'
    - '登録フォームからのユーザ登録': 'howto/howto03.md'
    - 'パスワードを忘れた！': 'howto/howto04.md'
  - '一般ユーザマニュアル': '一般機能/index.md'
  - '管理者ユーザマニュアル': '管理者機能/index.md'
  - 'リリースノート': 'releasenote/index.md'
  - '利用規約・プライバシーポリシー': 'policy.md'


